version: '3.9'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres 
    networks:
      - app-network

  postgres:
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_USER: mohamed
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: rented_db
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  
volumes:
  pgadmin_data: