version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres 
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: mohamed
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: rented_db
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge